### ISSUE TITLE
Chat with page: cursor placemenent

### ISSUE THREAD

**Issue by zefhemel** [justyns/silverbullet-ai#1]
I think I will become a heavy user of the chat with AI feature, but this is kind of annoying:

![CleanShot 2024-02-23 at 09 37 13](https://github.com/justyns/silverbullet-ai/assets/59073/7a2ca270-f88b-4f17-9e5c-c44cbeed3148)

After hitting Cmd-Shift-Enter the cursor remains after the assistant's text, and doesn't put it ready for me to continue typing.

I think the best UX would be:

The moment the user hits Cmd-Shift-Enter, a new `**assistant:**` and `**user:**` prompt is added and the cursor is placed there, at the same time above it the results stream in from AI and placed after the assistant prompt using what I described on Discord:

```
await editor.dispatch({
      changes: {
        from: 123,
        to: 123,
        insert: “whatever”,
      },
    })
```

Minor note: showing the "Contacting LLM" notification gets redundant quite quickly, I would not show it in this conext.

**Comment by justyns** [comment]
Thanks for the feedback!

I agree the cursor moving was kind of weird.  I thought I would like it (so that the page scrolls automatically) but it annoyed me more than not.  I went with your idea of pre-creating the "user:" part before waiting for the full response to complete.

For the "Contacting LLM" notification - I want some way to know that the user is actually waiting on something.  For OpenAI and most other hosted LLM apis, the initial streaming starts pretty fast.  But for locally hosted ones, the first response can take some time for the model to initially load.   What do you think about a loading/spinner after the `assistant: ` prompt until the stream starts?   

I'll need to figure out how to actually do that, but I think it would be less disrupting, especially on mobile.

![cursor-not-following](https://github.com/justyns/silverbullet-ai/assets/215985/11eafdb1-32e1-4477-80b3-84df4ef04e5a)

**Comment by zefhemel** [comment]
That sounds good, but a spinner may be technically hard. Perhaps just a "Let me think 🤔 " text that is later replaced?
